services:
  minio:
    user: "${DOCKER_USER:-1000}"
    volumes:
      - ./data/media:/data
    environment:
      - MINIO_ROOT_USER=impress
      - MINIO_ROOT_PASSWORD=password

  frontend-development:
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - HOST=0.0.0.0
      - NEXT_PUBLIC_API_ORIGIN=http://172.212.108.66:8071

volumes:
  docs_minio_data:
    name: docs_minio_data

